## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [2]:
df = pd.read_excel("aiml_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
10,4MW24AI011,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
11,4MW24AI013,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-06,2
13,4MW24AI015,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-29,3
19,4MW24AI022,KUNDAR KASHISH CHANDRA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
20,4MW24AI023,LAKSHITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
23,4MW24AI026,MAYUR,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
24,4MW24AI027,MOHAMMED SIMAK,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-22,5
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
28,4MW24AI031,PAVITHRA NAYAK,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
34,4MW24AI037,RAKESH HEGDE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-10-06,2
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42%,Critical,16 more,2026-10-06,2
40,4MW24AI044,SHODAN B POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-10,0
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-09-08,9
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
46,4MW24AI050,SPOORTHI,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-09,1
48,4MW24AI053,SUPRITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
49,4MW24AI054,TEJAS,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
50,4MW24AI055,TRIPTHI H PADMASHALI,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
52,4MW24AI057,VANDANA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58%,Critical,8 more,2026-09-25,4
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-10,0
55,4MW24AI060,YASHASVI K POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
56,4MW24AI061,Raksha,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
57,4MW25AI400,Dhananjay,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-08,9

#### Section 1: Data Inspection

In [3]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------
print("First 10 rows of the DataFrame:")
df.head(10)

First 10 rows of the DataFrame:

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1

In [4]:
print("\nShape of the DataFrame:")
df.shape

Shape of the DataFrame:

(59, 12)

In [5]:
print("\nData types of each column:")
df.dtypes

Data types of each column:

Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [6]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------
print("Missing values in each column:")
df.isnull().sum()

Missing values in each column:

Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

In [7]:
print("\nColumns with missing values:")
df.isnull().sum()[df.isnull().sum() > 0]

Columns with missing values:

Series([], dtype: int64)

In [8]:
df["Last Present Date"].astype(str).str.strip().str.lower().eq("never").sum()

np.int64(2)

In [9]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------
df.columns = (df.columns.str.strip()
              .str.lower()
              .str.replace(" ", "_")
              .str.replace("%", "pct"))
df.columns.tolist()

['roll_no',
 'student_name',
 'subject',
 'total_classes',
 'present',
 'absent',
 'excused',
 'attendance_pct',
 'status',
 'classes_needed_(75pct)',
 'last_present_date',
 'consecutive_absences']

In [10]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------
df["attendance_pct"] = pd.to_numeric(df["attendance_pct"], errors="coerce")
df["last_present_date"] = pd.to_datetime(df["last_present_date"], errors="coerce")
df[["attendance_pct", "last_present_date"]].dtypes

attendance_pct              float64
last_present_date    datetime64[us]
dtype: object

#### Section 2: Filtering & Selection

In [11]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
df[df["status"] == "Critical"].sort_values(by="attendance_pct", ascending=True)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_(75pct),last_present_date,consecutive_absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,NaN,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,NaN,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,NaN,Critical,32 more,2026-09-22,5
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,NaN,Critical,12 more,2026-10-06,2
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-09-29,3
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,NaN,Critical,28 more,2026-10-06,2
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-09-22,5
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-10-06,2
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-10-06,2
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-10-06,2
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,NaN,Critical,36 more,NaT,12
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,NaN,Critical,36 more,NaT,12
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,NaN,Critical,32 more,2026-10-06,2
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,NaN,Critical,20 more,2026-10-06,2
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-10-06,2
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,NaN,Critical,16 more,2026-10-06,2
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,NaN,Critical,28 more,2026-09-08,9
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,NaN,Critical,28 more,2026-10-06,2
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,NaN,Critical,12 more,2026-10-09,1
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,NaN,Critical,20 more,2026-10-06,2
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,NaN,Critical,8 more,2026-09-25,4
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,NaN,Critical,4 more,2026-10-10,0
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,NaN,Critical,32 more,2026-09-08,9

In [12]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
df[df["present"] == 0][["roll_no", "student_name", "consecutive_absences"]]

       roll_no        student_name  consecutive_absences
32  4MW24AI035          RAJATH K K                    12
33  4MW24AI036  RAJU ASHOKA RATHOD                    12

In [13]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
#(a) 
df.loc[df["status"] == "Safe"]

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_(75pct),last_present_date,consecutive_absences
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,NaN,Safe,✓ Met,2026-10-10,0
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-09,1
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-09,1
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-09,1
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-09,1
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,NaN,Safe,✓ Met,2026-10-10,0
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0

In [14]:
#(b)
df.iloc[:15, 1:6]

,student_name,subject,total_classes,present,absent
0,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4
1,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4
2,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11
3,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1
4,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2
5,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2
6,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2
7,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0
8,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2
9,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3
10,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3
11,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3
12,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6
13,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3
14,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1

In [15]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------
df[df["consecutive_absences"] >= 5][["student_name", "status", "last_present_date"]]

          student_name    status last_present_date
2               ADITYA  Critical        2026-09-22
25      MOURYA RAJ H N  Critical        2026-09-22
32          RAJATH K K  Critical               NaT
33  RAJU ASHOKA RATHOD  Critical               NaT
41             SHRAVYA  Critical        2026-09-08
58          Omkar Rane  Critical        2026-09-08

### Section 3: Grouping & Aggregation

In [16]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
df.groupby("status").agg(
    student_count=("student_name", "count"),
    average_attendance=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
)

          student_count  average_attendance  max_consecutive_absences
status
Critical             23                 NaN                        12
Safe                 13                 NaN                         1
Warning              23                 NaN                         2

In [17]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------
df["attendance_category"] = pd.cut(
    df["attendance_pct"],
    bins=[-float("inf"), 0.60, 0.75, 0.90, float("inf")],
    labels=["Poor", "Average", "Good", "Excellent"],
    right=False
)
df.groupby("attendance_category", observed=False)["student_name"].count()

attendance_category
Poor         0
Average      0
Good         0
Excellent    0
Name: student_name, dtype: int64

In [18]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------
df[["total_classes", "present", "absent"]].agg("sum")

total_classes    708
present          451
absent           257
dtype: int64

In [19]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------
df.groupby("status").agg(
    present_min=("present", "min"),
    present_max=("present", "max"),
    present_mean=("present", "mean"),
    total_absent=("absent", "sum")
)

          present_min  present_max  present_mean  total_absent
status
Critical            0            8      3.608696           193
Safe               11           12     11.153846            11
Warning             9           10      9.695652            53

### Section 4: Feature Engineering & Transformation

In [20]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------
df["risk_score"] = (df["absent"] * 0.4) + (df["consecutive_absences"] * 0.6)
df.nlargest(10, "risk_score")[["roll_no", "student_name", "risk_score"]]

       roll_no                 student_name  risk_score
32  4MW24AI035                   RAJATH K K        12.0
33  4MW24AI036           RAJU ASHOKA RATHOD        12.0
58  4MW25AI401                   Omkar Rane         9.8
41  4MW24AI045                      SHRAVYA         9.4
2   4MW24AI003                       ADITYA         7.4
25  4MW24AI028               MOURYA RAJ H N         6.6
35  4MW24AI038                       RASHMI         5.6
18  4MW24AI021                     KISHAN J         5.4
22  4MW24AI025                     MANMITHA         5.2
44  4MW24AI048  SINCHANA (SUNDARA MADIVALA)         5.2

In [21]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------
df["classes_needed_numeric"] = df["classes_needed_(75pct)"].astype(str).str.extract(r"(\d+)").fillna(0).astype(int)
df[["classes_needed_(75pct)", "classes_needed_numeric"]]

   classes_needed_(75pct)  classes_needed_numeric
0                  4 more                       4
1                  4 more                       4
2                 32 more                      32
3                   ✓ Met                       0
4                   ✓ Met                       0
5                   ✓ Met                       0
6                   ✓ Met                       0
7                   ✓ Met                       0
8                   ✓ Met                       0
9                   ✓ Met                       0
10                  ✓ Met                       0
11                  ✓ Met                       0
12                12 more                      12
13                  ✓ Met                       0
14                  ✓ Met                       0
15                  ✓ Met                       0
16                  ✓ Met                       0
17                  ✓ Met                       0
18                24 more                      24
19                  ✓ Met                       0
20                  ✓ Met                       0
21                  ✓ Met                       0
22                28 more                      28
23                  ✓ Met                       0
24                  ✓ Met                       0
25                24 more                      24
26                  ✓ Met                       0
27                24 more                      24
28                  ✓ Met                       0
29                  ✓ Met                       0
30                24 more                      24
31                24 more                      24
32                36 more                      36
33                36 more                      36
34                  ✓ Met                       0
35                32 more                      32
36                20 more                      20
37                24 more                      24
38                  ✓ Met                       0
39                16 more                      16
40                  ✓ Met                       0
41                28 more                      28
42                  ✓ Met                       0
43                  ✓ Met                       0
44                28 more                      28
45                  ✓ Met                       0
46                  ✓ Met                       0
47                12 more                      12
48                  ✓ Met                       0
49                  ✓ Met                       0
50                  ✓ Met                       0
51                20 more                      20
52                  ✓ Met                       0
53                 8 more                       8
54                 4 more                       4
55                  ✓ Met                       0
56                  ✓ Met                       0
57                  ✓ Met                       0
58                32 more                      32

In [22]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------
df["attendance_flag"] = df["attendance_pct"].apply(lambda x: "Defaulter" if x < 0.75 else "Safe")
df[["student_name", "attendance_pct", "attendance_flag"]]

                            student_name  attendance_pct attendance_flag
0                               ABHIJITH             NaN            Safe
1                     ABHISHEK KRISHNA P             NaN            Safe
2                                 ADITYA             NaN            Safe
3                      AKSHATA JAKAREDDY             NaN            Safe
4                                 ANANYA             NaN            Safe
5                            ANANYASHREE             NaN            Safe
6                  ANKITA TARANATH MESTA             NaN            Safe
7                      ANVITH S SHERIGAR             NaN            Safe
8                                APEKSHA             NaN            Safe
9                ARLENE VELORA FERNANDES             NaN            Safe
10                              ASHRITHA             NaN            Safe
11                         AYESHA REEMAN             NaN            Safe
12                     DHANRAJ L POOJARY             NaN            Safe
13                           DHANYATHA R             NaN            Safe
14                            G BHUPATHE             NaN            Safe
15                     HARSHAL G POOJARY             NaN            Safe
16                           JNANESH . S             NaN            Safe
17             KEERTHAN KRISHNA SHERIGAR             NaN            Safe
18                              KISHAN J             NaN            Safe
19                KUNDAR KASHISH CHANDRA             NaN            Safe
20                             LAKSHITHA             NaN            Safe
21                        MANEESH SHETTY             NaN            Safe
22                              MANMITHA             NaN            Safe
23                                 MAYUR             NaN            Safe
24                        MOHAMMED SIMAK             NaN            Safe
25                        MOURYA RAJ H N             NaN            Safe
26                       MUHAMMED NASHIT             NaN            Safe
27                                 NAVYA             NaN            Safe
28                        PAVITHRA NAYAK             NaN            Safe
29                             PRAGNYA R             NaN            Safe
30                          PRAMOD ACHAR             NaN            Safe
31                            RAJATH H S             NaN            Safe
32                            RAJATH K K             NaN            Safe
33                    RAJU ASHOKA RATHOD             NaN            Safe
34                          RAKESH HEGDE             NaN            Safe
35                                RASHMI             NaN            Safe
36                                RITHIN             NaN            Safe
37                                SANIKA             NaN            Safe
38                            SHAMANTH K             NaN            Safe
39               SHETTY RASHIK RATHNAKAR             NaN            Safe
40                      SHODAN B POOJARY             NaN            Safe
41                               SHRAVYA             NaN            Safe
42                    SHREESH A DEVADIGA             NaN            Safe
43                       SHRIYA DEVADIGA             NaN            Safe
44           SINCHANA (SUNDARA MADIVALA)             NaN            Safe
45  SINCHANA (MURALI KUPPAYYA MOGAVEERA)             NaN            Safe
46                              SPOORTHI             NaN            Safe
47                           SUPRAJA S M             NaN            Safe
48                              SUPRITHA             NaN            Safe
49                                 TEJAS             NaN            Safe
50                  TRIPTHI H PADMASHALI             NaN            Safe
51                                 VAMSH             NaN            Safe
52                               VANDANA             NaN            Safe
53                         VIGNESH ADIGA             NaN            Safe
54                              VIHAAN S             NaN            Safe
55                    YASHASVI K POOJARY             NaN            Safe
56                                Raksha             NaN            Safe
57                             Dhananjay             NaN            Safe
58                            Omkar Rane             NaN            Safe

In [23]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------
df["attendance_range"] = pd.cut(
    df["attendance_pct"],
    bins=[0, 0.50, 0.75, 0.90, 1.00],
    labels=["Critical", "Warning", "Good", "Excellent"],
    include_lowest=True
)
df[["student_name", "attendance_pct", "attendance_range"]]

                            student_name  attendance_pct attendance_range
0                               ABHIJITH             NaN              NaN
1                     ABHISHEK KRISHNA P             NaN              NaN
2                                 ADITYA             NaN              NaN
3                      AKSHATA JAKAREDDY             NaN              NaN
4                                 ANANYA             NaN              NaN
5                            ANANYASHREE             NaN              NaN
6                  ANKITA TARANATH MESTA             NaN              NaN
7                      ANVITH S SHERIGAR             NaN              NaN
8                                APEKSHA             NaN              NaN
9                ARLENE VELORA FERNANDES             NaN              NaN
10                              ASHRITHA             NaN              NaN
11                         AYESHA REEMAN             NaN              NaN
12                     DHANRAJ L POOJARY             NaN              NaN
13                           DHANYATHA R             NaN              NaN
14                            G BHUPATHE             NaN              NaN
15                     HARSHAL G POOJARY             NaN              NaN
16                           JNANESH . S             NaN              NaN
17             KEERTHAN KRISHNA SHERIGAR             NaN              NaN
18                              KISHAN J             NaN              NaN
19                KUNDAR KASHISH CHANDRA             NaN              NaN
20                             LAKSHITHA             NaN              NaN
21                        MANEESH SHETTY             NaN              NaN
22                              MANMITHA             NaN              NaN
23                                 MAYUR             NaN              NaN
24                        MOHAMMED SIMAK             NaN              NaN
25                        MOURYA RAJ H N             NaN              NaN
26                       MUHAMMED NASHIT             NaN              NaN
27                                 NAVYA             NaN              NaN
28                        PAVITHRA NAYAK             NaN              NaN
29                             PRAGNYA R             NaN              NaN
30                          PRAMOD ACHAR             NaN              NaN
31                            RAJATH H S             NaN              NaN
32                            RAJATH K K             NaN              NaN
33                    RAJU ASHOKA RATHOD             NaN              NaN
34                          RAKESH HEGDE             NaN              NaN
35                                RASHMI             NaN              NaN
36                                RITHIN             NaN              NaN
37                                SANIKA             NaN              NaN
38                            SHAMANTH K             NaN              NaN
39               SHETTY RASHIK RATHNAKAR             NaN              NaN
40                      SHODAN B POOJARY             NaN              NaN
41                               SHRAVYA             NaN              NaN
42                    SHREESH A DEVADIGA             NaN              NaN
43                       SHRIYA DEVADIGA             NaN              NaN
44           SINCHANA (SUNDARA MADIVALA)             NaN              NaN
45  SINCHANA (MURALI KUPPAYYA MOGAVEERA)             NaN              NaN
46                              SPOORTHI             NaN              NaN
47                           SUPRAJA S M             NaN              NaN
48                              SUPRITHA             NaN              NaN
49                                 TEJAS             NaN              NaN
50                  TRIPTHI H PADMASHALI             NaN              NaN
51                                 VAMSH             NaN              NaN
52                               VANDANA             NaN              NaN
53                         VIGNESH ADIGA             NaN              NaN
54                              VIHAAN S             NaN              NaN
55                    YASHASVI K POOJARY             NaN              NaN
56                                Raksha             NaN              NaN
57                             Dhananjay             NaN              NaN
58                            Omkar Rane             NaN              NaN

### Section 5: Advanced Analysis

In [24]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------
pd.pivot_table(
    df,
    index="status",
    columns="attendance_category",
    values="student_name",
    aggfunc="count",
    fill_value=0
)

Empty DataFrame
Columns: []
Index: []

In [25]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------
df["base_name"] = df["student_name"].str.split().str[0].str.upper()
df[df.duplicated("base_name", keep=False)].sort_values("base_name")

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_(75pct),last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-10-06,2,NaN,4.8,24,Safe,NaN,RAJATH
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,NaN,Critical,36 more,NaT,12,NaN,12.0,36,Safe,NaN,RAJATH
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,NaN,Critical,28 more,2026-10-06,2,NaN,5.2,28,Safe,NaN,SINCHANA
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0,NaN,0.4,0,Safe,NaN,SINCHANA

In [26]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------
Student_Details = pd.DataFrame({
    "roll_no": df["roll_no"].unique(),
    "branch": ["AIML"] * len(df["roll_no"].unique()),
    "semester": [5] * len(df["roll_no"].unique())
})
merged_df = pd.merge(df, Student_Details, on="roll_no", how="inner")
merged_df

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_(75pct),last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name,branch,semester
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,NaN,Critical,4 more,2026-10-09,1,NaN,2.2,4,Safe,NaN,ABHIJITH,AIML,5
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,NaN,Critical,4 more,2026-10-09,1,NaN,2.2,4,Safe,NaN,ABHISHEK,AIML,5
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,NaN,Critical,32 more,2026-09-22,5,NaN,7.4,32,Safe,NaN,ADITYA,AIML,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0,NaN,0.4,0,Safe,NaN,AKSHATA,AIML,5
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.4,0,Safe,NaN,ANANYA,AIML,5
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.4,0,Safe,NaN,ANANYASHREE,AIML,5
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.4,0,Safe,NaN,ANKITA,AIML,5
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,NaN,Safe,✓ Met,2026-10-10,0,NaN,0.0,0,Safe,NaN,ANVITH,AIML,5
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.4,0,Safe,NaN,APEKSHA,AIML,5
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.8,0,Safe,NaN,ARLENE,AIML,5
10,4MW24AI011,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.8,0,Safe,NaN,ASHRITHA,AIML,5
11,4MW24AI013,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,NaN,Warning,✓ Met,2026-10-06,2,NaN,2.4,0,Safe,NaN,AYESHA,AIML,5
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,NaN,Critical,12 more,2026-10-06,2,NaN,3.6,12,Safe,NaN,DHANRAJ,AIML,5
13,4MW24AI015,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.8,0,Safe,NaN,DHANYATHA,AIML,5
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0,NaN,0.4,0,Safe,NaN,G,AIML,5
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-09,1,NaN,1.0,0,Safe,NaN,HARSHAL,AIML,5
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-09,1,NaN,1.0,0,Safe,NaN,JNANESH,AIML,5
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-09,1,NaN,1.0,0,Safe,NaN,KEERTHAN,AIML,5
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-09-29,3,NaN,5.4,24,Safe,NaN,KISHAN,AIML,5
19,4MW24AI022,KUNDAR KASHISH CHANDRA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-10,0,NaN,0.8,0,Safe,NaN,KUNDAR,AIML,5
20,4MW24AI023,LAKSHITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-10,0,NaN,0.8,0,Safe,NaN,LAKSHITHA,AIML,5
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0,NaN,0.4,0,Safe,NaN,MANEESH,AIML,5
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,NaN,Critical,28 more,2026-10-06,2,NaN,5.2,28,Safe,NaN,MANMITHA,AIML,5
23,4MW24AI026,MAYUR,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-06,2,NaN,2.0,0,Safe,NaN,MAYUR,AIML,5
24,4MW24AI027,MOHAMMED SIMAK,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,NaN,Warning,✓ Met,2026-10-06,2,NaN,2.4,0,Safe,NaN,MOHAMMED,AIML,5
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-09-22,5,NaN,6.6,24,Safe,NaN,MOURYA,AIML,5
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0,NaN,0.4,0,Safe,NaN,MUHAMMED,AIML,5
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-10-06,2,NaN,4.8,24,Safe,NaN,NAVYA,AIML,5
28,4MW24AI031,PAVITHRA NAYAK,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.4,0,Safe,NaN,PAVITHRA,AIML,5
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0,NaN,0.4,0,Safe,NaN,PRAGNYA,AIML,5
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-10-06,2,NaN,4.8,24,Safe,NaN,PRAMOD,AIML,5
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-10-06,2,NaN,4.8,24,Safe,NaN,RAJATH,AIML,5
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,NaN,Critical,36 more,NaT,12,NaN,12.0,36,Safe,NaN,RAJATH,AIML,5
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,NaN,Critical,36 more,NaT,12,NaN,12.0,36,Safe,NaN,RAJU,AIML,5
34,4MW24AI037,RAKESH HEGDE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.4,0,Safe,NaN,RAKESH,AIML,5
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,NaN,Critical,32 more,2026-10-06,2,NaN,5.6,32,Safe,NaN,RASHMI,AIML,5
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,NaN,Critical,20 more,2026-10-06,2,NaN,4.4,20,Safe,NaN,RITHIN,AIML,5
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,NaN,Critical,24 more,2026-10-06,2,NaN,4.8,24,Safe,NaN,SANIKA,AIML,5
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-09,1,NaN,1.0,0,Safe,NaN,SHAMANTH,AIML,5
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,NaN,Critical,16 more,2026-10-06,2,NaN,4.0,16,Safe,NaN,SHETTY,AIML,5
40,4MW24AI044,SHODAN B POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,NaN,Warning,✓ Met,2026-10-10,0,NaN,1.2,0,Safe,NaN,SHODAN,AIML,5
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,NaN,Critical,28 more,2026-09-08,9,NaN,9.4,28,Safe,NaN,SHRAVYA,AIML,5
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,NaN,Safe,✓ Met,2026-10-10,0,NaN,0.0,0,Safe,NaN,SHREESH,AIML,5
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0,NaN,0.4,0,Safe,NaN,SHRIYA,AIML,5
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,NaN,Critical,28 more,2026-10-06,2,NaN,5.2,28,Safe,NaN,SINCHANA,AIML,5
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,NaN,Safe,✓ Met,2026-10-10,0,NaN,0.4,0,Safe,NaN,SINCHANA,AIML,5
46,4MW24AI050,SPOORTHI,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.4,0,Safe,NaN,SPOORTHI,AIML,5
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,NaN,Critical,12 more,2026-10-09,1,NaN,3.0,12,Safe,NaN,SUPRAJA,AIML,5
48,4MW24AI053,SUPRITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.4,0,Safe,NaN,SUPRITHA,AIML,5
49,4MW24AI054,TEJAS,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-06,2,NaN,2.0,0,Safe,NaN,TEJAS,AIML,5
50,4MW24AI055,TRIPTHI H PADMASHALI,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.8,0,Safe,NaN,TRIPTHI,AIML,5
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,NaN,Critical,20 more,2026-10-06,2,NaN,4.4,20,Safe,NaN,VAMSH,AIML,5
52,4MW24AI057,VANDANA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.4,0,Safe,NaN,VANDANA,AIML,5
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,NaN,Critical,8 more,2026-09-25,4,NaN,4.4,8,Safe,NaN,VIGNESH,AIML,5
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,NaN,Critical,4 more,2026-10-10,0,NaN,1.6,4,Safe,NaN,VIHAAN,AIML,5
55,4MW24AI060,YASHASVI K POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.4,0,Safe,NaN,YASHASVI,AIML,5
56,4MW24AI061,Raksha,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-09,1,NaN,1.4,0,Safe,NaN,RAKSHA,AIML,5
57,4MW25AI400,Dhananjay,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,NaN,Warning,✓ Met,2026-10-06,2,NaN,2.0,0,Safe,NaN,DHANANJAY,AIML,5
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,NaN,Critical,32 more,2026-09-08,9,NaN,9.8,32,Safe,NaN,OMKAR,AIML,5

In [27]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------
df[df["status"] == "Critical"].to_csv("critical_students.csv", index=False)
df.groupby("status").agg(
    student_count=("student_name", "count"),
    average_attendance=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
).to_csv("status_summary.csv")
df.nlargest(10, "risk_score").to_csv("top10_risk_students.csv", index=False)